version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb://root:password@mongo:27017/app
      MONGO_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  storage:
    image: docker.io/bitnami/minio:lastest
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - minionetwork
    volumes:
      - "minio_data:/data"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: pasword
      MINIO_DEFAULT_BUCKETS: app

volumes:
  mongo-data:
