version: "3.8"

services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     NODE_ENV: production
  #     APP_URL: http://localhost:5000
  #     MONGO_URL: mongodb://root:password@mongo:27017
  #     MINIO_ROOT_USER: root
  #     MINIO_ROOT_PASSWORD: password
  #     MINIO_DEFAULT_BUCKETS: app
  #     MONGO_CONFIG_BASICAUTH: false
  #     OPENAI_API_KEY: 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
  #   depends_on:
  #     - mongo
  #     - storage

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   environment:
  #     VITE_BACKEND_URL: http://localhost:5000
  #   depends_on:
  #     - backend

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

  storage:
    image: docker.io/bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
      MINIO_DEFAULT_BUCKETS: app
      MINIO_SERVER_URL: http://localhost:24001

volumes:
  mongo_data:
  mongo_config:
  minio_data:
